version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5001:5001" 
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80" 
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "8081:8080" 
      - "50001:50000" 
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped

volumes:
  jenkins_home:
